#pragma config(Sensor, S1,     distance,       sensorEV3_IRSensor)
#pragma config(Sensor, S3,     color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          grab,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//turn method to avoid walls
void turn(bool x){
	int speed=25;
	int turnTime=1670;

	if (x){
		motor[motorB]=-speed;
		motor[motorC]=speed;

		sleep(turnTime);}

	if (!x){
		motor[motorB]=speed;
		motor[motorC]=-speed;

		sleep(turnTime);}
		//Goes forward
		motor[motorB]=speed;
		motor[motorC]=speed;
		sleep(2000);

		//turn again
		if (x){
		motor[motorB]=-speed;
		motor[motorC]=speed;

		sleep(turnTime);}

		if (!x){
		motor[motorB]=speed;
		motor[motorC]=-speed;
		sleep(turnTime);}

}
	//true = grab flase = release
void pickUp(bool grab){
	int move =50;
	int time = 700;


	if(grab){
	motor[motorA]=move;
	sleep(time);}


	else{
			motor[motorA]=-move;
	sleep(time);}
	motor[motorA]=0;

	}

void goHome(bool x){
	int speed=25;
	int turnTime=1670;
if(x){
	//goes right
		motor[motorB]=speed;
		motor[motorC]=-speed;
		sleep(turnTime);
		//goes to wallif
		while(SensorValue(S1)>20){
		motor[motorB]=speed;
		motor[motorC]=speed;}
		//turn right
		motor[motorB]=speed;
		motor[motorC]=-speed;
		sleep(turnTime);

		//goes straight till wall drops
		while(SensorValue(S1)>20){
		motor[motorB]=speed;
		motor[motorC]=speed;}
		pickUp(false);
		stopAllTasks();

}
else{
	//go forwar untill wall
		while(SensorValue(S1)>20){
		motor[motorB]=speed;
		motor[motorC]=speed;}
		//left turn
		motor[motorB]=-speed;
		motor[motorC]=speed;
		sleep(turnTime);
		//go to wall
		while(SensorValue(S1)>20){
		motor[motorB]=speed;
		motor[motorC]=speed;}
		pickUp(false);
		stopAllTasks();
}




}

task main()
{bool turnBool = true;
	bool pickedUp=false;
	//true = left

	PlaySoundFile("megalovania.mp3");

	while(true){

		//move forward
		motor[motorB]=50;
	  motor[motorC]=50;


		//check colors


		//check distance
	  if(SensorValue(S1)<20){
	  		playTone(400, 20);
	  		turn(turnBool);
	  	turnBool=!turnBool;

	  	}
	  	if(getColorName(S3)==colorWhite&&pickedUp==false){
	  		pickUp(true);
	  		pickedUp=true;
	  		goHome(turnBool);

	  		}
	}










}
